### ISSUE TITLE
No keyboard support

### ISSUE THREAD

**Issue by stringyland** [sapegin/social-likes#101]
The buttons do not take keyboard focus; this prevents screenreader users and people with mobility/dexterity issues from relying on the keyboard to use the buttons. Div elements don't take keyboard focus in the browser at their default setting. 

Recommend using an element which takes focus and click events by default (link or button) instead of a div or span. Alternatively, add a tabindex=1 attribute to make the divs focusable, but then need to add keyboard support for keyboard Enter event in the script. 

Also would need to add a :focus style selector to the existing :hover styles to show when button has focus.

**Comment by sapegin** [comment]
Implemented in [Social Likes Next](https://github.com/sapegin/social-likes-next). Feel free to submit a pull request if you want it in the classic Social Likes too.
