### ISSUE TITLE
Can this be converted to likes plugin?

### ISSUE THREAD

**Issue by danyj** [sapegin/social-likes#102]
This is more of a share plugin not likes and we cant use different links for different page for example 
my gplus page is not same as my website or my twitter, so this plugin is useful for blog posts shares but not for a website or facbook page/gplus page/twitter page likes .

**Comment by sapegin** [comment]
Sorry, I don’t understand what you want.

**Comment by danyj** [comment]
Example: 
my homepage is mybusiness.com
gplus: https://plus.google.com/+mybusinessName ( has 1000 followers )
twitter: mybusinessName ( has 2000 followers ) 
fbpage:  facebook.com/mybusinessName ( has 15K likes )

I want to add your plugin on my homepage so that people like the business pages on all social media
With current code they cant do that, they can only share a particular page like 

mybusiness.com/myblog/my-blog-post.html

**Comment by sapegin** [comment]
This plugin is for sharing a specific URL (most probably current page).

**Comment by danyj** [comment]
OK bud, than the name should be Social - shares not likes.
