### ISSUE TITLE
Google+ counter is parsed incorrectly

### ISSUE THREAD

**Issue by avlukanin** [sapegin/social-likes#105]
The response is looked like this from Russia:
    `services.gplus.cb("3.456");`
and like this from Europe:
    `services.gplus.cb("3456");`

In Russia the counter is rendered as `3` instead of `3456`.

**Comment by sapegin** [comment]
It’s strange, I got:

```
services.gplus.cb("9052");
```

Could you give me a link with such behavior?

**Comment by avlukanin** [comment]
This happens from time to time. Right now the response is `services.gplus.cb("3572");`. I was lucky to catch it and see the response in the Networks tab.

**Comment by avlukanin** [comment]
I caught it again:
![](https://4.downloader.disk.yandex.ru/preview/9382ab07499d4dca8399cc77ec914c15/mpfs/tr98Ookxe8BkaOZLG0h6YMBQb7R68wzvveBXDHpv5QFUfoy-Dqgv7z5cqWudzycfgs8oynR7N7JZF79hSEQg2A%3D%3D?uid=0&filename=wronggppcounterpng&disposition=inline&hash=&limit=0&content_type=image%2Fpng&size=XXL&crop=0)

**Comment by sapegin** [comment]
OK, I’ll fix it.

**Comment by avlukanin** [comment]
I think, there will be no float counters, so there should be something like:
```javascript
		updateCounter: function(number) {
			if (typeof number == 'string') {
				number.replace('.', '');
			}
			number = parseInt(number, 10) || 0;
```

**Comment by avlukanin** [comment]
Well, I guess, they just show thousands, when there is a dot. See the screenshots:
![](https://leto35h.storage.yandex.net/rdisk/3a76ef180b4454df746f1347f39cc70b/mpfs/0UWwIqy9lihfdlAJrtCae8BQb7R68wzvveBXDHpv5QEjaBKi1duxDF0J8DEw-sqElZG1B_9MVHe7uA7kJwOb9g==?uid=0&filename=2015-01-29%2018-21-02%20strange%20gpp.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&rtoken=cb95dfe8ae1bbe75a2f010bb58d5e500&rtimestamp=54ca3558&force_default=no)

2 minutes later:

![](https://leto25d.storage.yandex.net/rdisk/a77f8b1bcc862febb1eb736a19eed04e/mpfs/EytXa4OyZad2qyQ_sE5tI_kN_sF_0BF0gMzxNNB76XG42TIMn-AsLQ7NA3DnONCyy46LVzCCRRxyjY395Pd_rw==?uid=0&filename=2015-01-29%2018-23-02%20strange%20gpp.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&rtoken=dcaf6fadf5d9d02e3700029359a24e5d&rtimestamp=54ca35f4&force_default=no)
