### ISSUE TITLE
theme with one share counter on all social networks

### ISSUE THREAD

**Issue by sheo13666** [sapegin/social-likes#110]

**Comment by sapegin** [comment]
Sorry, I don’t understand.

**Comment by sheo13666** [comment]
@sapegin example https://cache.addthiscdn.com/www/1501130e9b06e/style/images/dashboard/gallery/inline-share.png

**Comment by sapegin** [comment]
I’m sure it’s possible to make something like that using Social Likes.

**Comment by sheo13666** [comment]
@sapegin Make ready theme for use

**Comment by sapegin** [comment]
Nope, sorry.

**Comment by sheo13666** [comment]
@sapegin why? If you make this theme ready it will be very convenient.

**Comment by sapegin** [comment]
Because I already have an *interesting* and *paid* job. I’m not going to implement features for one user that I personally consider as bad.

**Comment by sheo13666** [comment]
@sapegin i create pr for this feature

**Comment by sapegin** [comment]
I won’t accept it.

**Comment by sheo13666** [comment]
@sapegin Why? this will not affect your time
