### ISSUE TITLE
Google+ and forceUpdate

### ISSUE THREAD

**Issue by shkarupa-alex** [sapegin/social-likes#111]
I've got in issue with G+ when trying to code lazy counter initialization.
In the list of news i create social likes object on each of news that in viewport.
Everything works well except G+. It returns correct counter only for the first news item. With other it does't make request  (even if i use forceUpdate: true).

It goes wrong in this part of code:
			counter: function(jsonUrl, deferred) {
				var options = services.plusone;
				if (options._) {
					// Reject all counters except the first because Yandex Share counter doesn’t return URL
					deferred.reject();
					return;
				}

So, it would be cool if forceUpdate will work in this case

**Comment by sapegin** [comment]
Yeah, that probably would work fine. But I’m not sure I know how to implement it without too many hacks. Will be happy to merge a pull request :star2:

**Comment by im-denisenko** [comment]
This part of code was deleted from gplus in #115, but added to another service in #114.
I guess this issue should be either closed or renamed.

**Comment by sapegin** [comment]
@im-denisenko Yep.
