### ISSUE TITLE
Popup position for two monitors

### ISSUE THREAD

**Issue by pix666** [sapegin/social-likes#112]
При работе на двух мониторах, всплывающее окно появляется прижатым к границе браузера:
http://joxi.ru/K823055S40aWAO

Могу предложить вариант решения: добавить window.screenLeft к координате "left" окна.

**Comment by pix666** [comment]
Дополнение: для мозиллы это screen.left:
http://stackoverflow.com/a/16861050

**Comment by sapegin** [comment]
Please use English when posting to this project.

**Comment by pix666** [comment]
Here you are not so principled:
https://github.com/sapegin/social-likes/issues/55
Well... That's my English answer for you: screw you man I'm going home.
![screw you](http://deadnancy.com/blog/images/cartman_finger.jpg)
