### ISSUE TITLE
problem on likes

### ISSUE THREAD

**Issue by gjmbo** [sapegin/social-likes#116]
Hi... i'm tryng your Social Likes (http://www.tiamoperche.it) but i have a problem:
On other sites is possible to make only one like on a post (like is associated on fb user) but with your plugin is possible to make as many like you want with the same fb user... 
Have you a solution for this?

Tanks

**Comment by sapegin** [comment]
The buttons know nothing about users (and actually can’t). 

https://github.com/sapegin/social-likes#likes-or-shares
