### ISSUE TITLE
Add extra Icons

### ISSUE THREAD

**Issue by tmblog** [sapegin/social-likes#118]
While tumblr doesn't allow share numbers I'd like to add the icon for tumblr and whatsapp, can this be achieved within this?

**Comment by sapegin** [comment]
Why don’t you just read the docs?

https://github.com/sapegin/social-likes#adding-your-own-button

**Comment by tmblog** [comment]
Hi yes sorry, I did follow what you've written. But my icons aren't showing up. So here's what I did.

added to social-likes.js
tumblr: {
        popupUrl: 'http://www.tumblr.com/share/link?url={url}&description={title}',
        popupWidth: 650,
        popupHeight: 500
    },

Added this to the flat css
.social-likes__button_tumblr{background: #34465D;}
.social-likes__icon_tumblr{background: url(http://quotepixels.com/img/tumblr.png) no-repeat 2px 3px;}

Then added the html
<div class="tumblr" title="Share on Tumblr"></div>

But here's what I get.

![capture](https://cloud.githubusercontent.com/assets/11068215/6319120/4f7ba504-baa9-11e4-9da9-ad24e8e2180b.PNG)

Would appreciate any pointers. Excellent plugin btw!

**Comment by sapegin** [comment]
Could you post it somewhere like jsfiddle.net?

**Comment by tmblog** [comment]
Thanks for the reply, I've put it up on codepen. With bg colour and and chars as fallback but you can take a look.

http://codepen.io/anon/pen/RNyBrV

**Comment by sapegin** [comment]
You’re trying to add image icons to a skin that uses web font. In your case you need to add width and height to `.social-likes__icon_tumblr`.

(Though it’s very bad idea to mix vector and bitmap icons.)

**Comment by tmblog** [comment]
Thanks for that, is this a font that you've created? How can I add other vectors to it?

**Comment by sapegin** [comment]
[Of course](https://github.com/sapegin/social-likes/blob/master/src/Gruntfile.js#L69-L84).
