### ISSUE TITLE
Make an SVG icons to Birman style

### ISSUE THREAD

**Issue by iCr** [sapegin/social-likes#119]
Hi there. Birman style is excellent, but png low-res icons make it ugly on retina displays.
Thanks.

**Comment by sapegin** [comment]
It’s planned but it’s not that easy.

**Comment by iCr** [comment]
Ok, it`s not easy, really.

**Comment by andreaslarsen** [comment]
A suggestion would be to use base64 encoded svg as background image instead of the iconfont - makes it much easier to replace and otherwise remix the icons.

**Comment by sapegin** [comment]
@andreaslarsen In that case we’ll have to use two copies of every icon: for normal and for hover states. I have same ideas how to implement it but didn’t have time yet.

**Comment by andreaslarsen** [comment]
You can just use filters

```
    .social-likes__icon_twitter
        background: url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIHZpZXdCb3g9IjAgMCAxMDAgMTAwIiB2ZXJzaW9uPSIxLjEiIHhtbDpzcGFjZT0icHJlc2VydmUiIHN0cm9rZS1saW5lam9pbj0icm91bmQiPjxwYXRoIGQ9Ik0xMDAgMjBjMC0xMS05LTIwLTIwLTIwbC02MCAwYy0xMSAwLTIwIDktMjAgMjBsMCA2MGMwIDExIDkgMjAgMjAgMjBsNjAgMGMxMSAwIDIwLTkgMjAtMjBsMC02MFpNMzYuNSA3OS43Yy04LjUgMC0xNi4zLTIuNS0yMy02LjcgMS4yIDAuMSAyLjQgMC4yIDMuNiAwLjIgNyAwIDEzLjUtMi40IDE4LjYtNi40IC02LjYtMC4xLTEyLjEtNC41LTE0LTEwLjQgMC45IDAuMiAxLjkgMC4zIDIuOCAwLjMgMS40IDAgMi43LTAuMiAzLjktMC41IC02LjktMS40LTEyLTcuNC0xMi0xNC43IDAtMC4xIDAtMC4xIDAtMC4yIDIgMS4xIDQuMyAxLjggNi44IDEuOSAtNC0yLjctNi43LTcuMy02LjctMTIuNSAwLTIuNyAwLjctNS4zIDItNy41IDcuNCA5LjEgMTguNCAxNSAzMC45IDE1LjYgLTAuMy0xLjEtMC40LTIuMi0wLjQtMy40IDAtOC4zIDYuNy0xNSAxNS0xNSA0LjMgMCA4LjIgMS44IDEwLjkgNC43IDMuNC0wLjcgNi42LTEuOSA5LjUtMy42IC0xLjEgMy41LTMuNSA2LjQtNi42IDguMyAzLTAuNCA1LjktMS4yIDguNi0yLjQgLTIgMy00LjUgNS42LTcuNSA3LjggMCAwLjYgMCAxLjMgMCAxLjkgMCAxOS44LTE1LjEgNDIuNi00Mi42IDQyLjZaIiBmaWxsPSIjNTVhY2VlIi8+PC9zdmc+')
            
        &:hover
            -webkit-filter: grayscale(100%) brightness(5)
            filter: grayscale(100%) brightness(5)
```

**Comment by sapegin** [comment]
@andreaslarsen Now, make this icon blue or orange.

**Comment by andreaslarsen** [comment]
http://codepen.io/noahblon/pen/HxKpJ

**Comment by sapegin** [comment]
@andreaslarsen Nice, but won’t work in IE.

**Comment by andreaslarsen** [comment]
I know, not currently but will come in project spartan and then just disable hover color change in older IE so it depends on how old browsers you will support

**Comment by sapegin** [comment]
@andreaslarsen In older IE === in any IE.

**Comment by andreaslarsen** [comment]
no, the old ones have ms-filter and one must expect most of the recent ones to do free upgrade to win 10 when it comes

**Comment by sapegin** [comment]
Implemented in [Social Likes Next](https://github.com/sapegin/social-likes-next). Feel free to submit a pull request if you want it in the classic Social Likes too.
