### ISSUE TITLE
Unused services ajax calls

### ISSUE THREAD

**Issue by mdesantis** [sapegin/social-likes#122]
Hello!

many thanks for this indispensable library :) We use social likes as follows:

```slim
.social-likes data-counters="yes" data-url = home_url
  .facebook
  .plusone
  .twitter
```

We have Facebook, Google+, Twitter, but we don't use Yandex. However, Yandex calls are performed by the application (calls llike `http://share.yandex.ru/gpp.xml?url=http%3A%2F%2Flocalhost%3A3000%2F&_=1426004789952`). These calls are quite annoying for us since yandex is far from us (we are in Italy) so often they take a lot of time.

Is this a bug or I should disable Yandex counter in some way?

Thank you!

**Comment by mdesantis** [comment]
I noticed that social likes code has Yandex code inside googleplus section: https://github.com/sapegin/social-likes/blob/master/src/social-likes.js#L119

Is it a refuse?

**Comment by sapegin** [comment]
We use Yandex API for Google+ because there’s no API by Google.

**Comment by mdesantis** [comment]
O.O thank you for the explanation and good work
