### ISSUE TITLE
New FB Api

### ISSUE THREAD

**Issue by tmblog** [sapegin/social-likes#124]
FB counts not working anymore. There was an update to the counters API any chance of an update?

**Comment by Murilirum** [comment]
I'm not having any issues with my facebook counters.

**Comment by tmblog** [comment]
My old ones are showing but not new ones. Ate your new shares showing ie anything shared today

**Comment by sapegin** [comment]
Do you really believe in it? Different APIs for likes that were made before some date and after?

**Comment by tmblog** [comment]
FQL is being deprecated.
https://developers.facebook.com/docs/reference/fql/link_stat/

**Comment by sapegin** [comment]
@tmblog Great, what should we do now? “Deprecated” doesn’t mean “doesn’t work”.

**Comment by tmblog** [comment]
It might do, check this
https://graph.facebook.com/fql?q=SELECT+total_count+FROM+link_stat+WHERE+url%3D%22http://quotepixels.com/quote/3596/nothing-declare-except-genius%22

vs

https://graph.facebook.com/?id=http://quotepixels.com/quote/3596/nothing-declare-except-genius

**Comment by sapegin** [comment]
`1` for both queries.

**Comment by tmblog** [comment]
Ok, thanks perhaps a caching issue on my side.
