### ISSUE TITLE
Zeroes count

### ISSUE THREAD

**Issue by fdumaine** [sapegin/social-likes#125]
Hello!

I'm using the single button mode.
If i put the zeroes : true, i got the count on the submenu.

But, i want to show the zeroes count not only on the submenu, near my Share button.

Can you told me if it possible and what is the parameter for that ?  :-)

Thank you and have a nice day!

**Comment by sapegin** [comment]
It’s not possible out of the box. But if you really need that (for some very strange reason) you can use [ready](https://github.com/sapegin/social-likes#readysocial-likes) event and draw zero on a button.
