### ISSUE TITLE
Responsive icons

### ISSUE THREAD

**Issue by larsenwork** [sapegin/social-likes#127]
Make the text disappear at a chosen break point so it's only icon + counter. 

Something similar to this (just with counters:) 

![rrssb-preview](https://cloud.githubusercontent.com/assets/3859425/7601037/cb76f248-f911-11e4-9755-1e0b9aef0c5c.png)

**Comment by sapegin** [comment]
This should be done in your site styles because I don’t know width of the container, only with of the browser window.
