### ISSUE TITLE
Ищет файл в папке jquery.min.js в social-likes

### ISSUE THREAD

**Issue by Carcous** [sapegin/social-likes#128]
Prestashop 1.5
Не работает ссылка
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
файл ищется в папке модуля, т. е. в social-likes, а там его нет.
Дело осложняется тем, что файл jquery.min.js подгружается выше по коду для слайдера и других модулей, т. е., выкачать его и положить в папку модуля не получится - нарушится работоспособность слайдера.
Судя по тому, что модуль работает, нужные функции всё же берутся из ранее подгруженного модуля, но браузер тратит время на попытки загрузить несуществующий файл внутри модуля.

**Comment by sapegin** [comment]
Please use English when posting to this project.
