### ISSUE TITLE
Modul searches a file jquery.min.js in social-likes folder

### ISSUE THREAD

**Issue by Carcous** [sapegin/social-likes#129]
CMS Prestashop 1.5
Modules ignores a link http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js and searches a file file jquery.min.js in social-likes folder.
This file jquery.min.js is loading early in a page code. It can't has putted in a module folder. It is conflicting with other modules.
How to disable a search a file jquery.min.js in social-likes folder?

**Comment by sapegin** [comment]
There’s no search for `jquery.min.js` in the plugin. You shouldn’t try to include jQuery twice on your page.
