### ISSUE TITLE
Неверные изображения

### ISSUE THREAD

**Issue by ToshuK** [sapegin/social-likes#132]
Почему-то кнопка Facebook стала захватывать неверные картинки. Раньше при нажатии поделиться отображались картинки записи блога, той записи, которой хочу поделиться. Сейчас-же почему-то картинка совершенно от другой записи. В чем может быть проблема?

Такой баг только с кнопкой Facebook, остальные подхватывают правильные изображения...

**Comment by yuranikolaev** [comment]
а что в консоли показывает? 
og:image правильный?
через facebook debugger прогонял?

**Comment by ToshuK** [comment]
Что за консоль?

Не прогонял через facebook debugger, первый раз об этом инструменте слышу...

Вот сайт, можешь взглянуть? - migbusiness ru

**Comment by yuranikolaev** [comment]
консоль, в смысле developer tools в хроме или ФФ

facebook debugger тут: https://developers.facebook.com/tools/debug/, пилишь в него ссылку и смотришь, как твою страницу видит фейсбук

на твоем сайте вобще (!) нет Open Graph тегов, их нужно добавить, в т.ч. og:image, указав в нем какую картинку шерить (можно указать статическую картинку, можно динамическую) 

так же на странице целая куча ошибок (их все надо исправить чтоб все работало), странно что вобще кнопки грузяться
![screen shot 2015-07-01 at 19 12 49](https://cloud.githubusercontent.com/assets/4644754/8459356/43f98fe8-2025-11e5-8ec4-5ddad3bb60c3.png)

**Comment by sapegin** [comment]
Please use English when posting to this project.

**Comment by ToshuK** [comment]
Не работает, поставил og:image - все равно старую картинку подхватывает...
