### ISSUE TITLE
Счетчики считают лайки или шеры?

### ISSUE THREAD

**Issue by yuranikolaev** [sapegin/social-likes#133]
Привет Артем!

Что конкретно считают (показывают посетителю) счетчики: лайки или шеры?
У меня в настоящий момент счетчик ФБ показывает лайки (в т.ч. сделанные в фейсбуке), в то время как кнопка-то шерит, а не лайкает =)

Есть какой нибудь вариант показывать именно количество шеров, а не лайков? (в документации не нашел, сам колхозить не хочу).

Большое спасибо за "плагин", использую на всех проектах, работает отлично.

**Comment by sapegin** [comment]
Please use English when posting to this project.
