### ISSUE TITLE
WebJar support - Missing license file is wrong case.

### ISSUE THREAD

**Issue by dianlight** [sapegin/social-likes#135]
If try to create a webjar from bower an error is throw because no license file is found.
The error can be corrected in 2 way:
1. Add "license": "MIT", to bower.json  or
2. Change the case of license.md to LICENSE.md
 

The webjar creation error:

Failed! No valid licenses found. No licenses were found. The acceptable licenses on BinTray are at: https://bintray.com/docs/api/#_footnote_1 License detection first uses the package metadata (e.g. package.json or bower.json) and falls back to looking for a LICENSE, LICENSE.txt, or LICENSE.md file in the master branch of the GitHub repo. Since these methods failed to detect a valid license you will need to work with the upstream project to add discoverable license metadata to a release or to the GitHub repo.

**Comment by sapegin** [comment]
That’s probably a bug of webjar itself (I have no idea what it is).
