### ISSUE TITLE
jquery-less implementation

### ISSUE THREAD

**Issue by iamstarkov** [sapegin/social-likes#136]
what do you think about it? is it in your roadmap or something?

**Comment by sapegin** [comment]
It’s good idea but I’m not sure I will have time to implement it. But I’ll be happy to merge a PR ;-)

**Comment by iamstarkov** [comment]
likely is already got jquery-free version, can you contact them and ask about help with likely itself?

**Comment by sapegin** [comment]
It’s not difficult to implement, I just don’t have a time and much interest in it now. But PRs are welcome.

**Comment by iamstarkov** [comment]
@volter9 do you think, you can help us?

**Comment by volter9** [comment]
I can share with my code, but I changed Artem's code really drastically that I'm unsure if Artem gonna be happy with it :)

As you know, likely is quite different from Social Likes (some features are thrown away from social likes, because Birman thinks they aren't needed). I rewrote likely's code first to vanilla, then moved "classes" and helpers into separate modules. The final
JS file is compiled via browserify.

If it's okay with Artem, then I can help with porting Social Likes, but I can't restore vanilla one-file source, I removed it, because I thought it's not needed.

**Comment by sapegin** [comment]
Maybe it’s better to extract some common stuff to a separate repositories and use them in Social Likes and Likely. Like counters fetching and info about social networks. And then eventually we could remove jQuery dependency from Social Likes.

**Comment by volter9** [comment]
I don't know. I think you should discuss it with Birman. I think he has reason for stripping some of the features from social likes and turning it into likely, and that reason is Birman YAGNI.

**Comment by sapegin** [comment]
I don’t suggest to replace Likely with Social Likes ;-) Just to share some code between the two projects.

**Comment by iamstarkov** [comment]
@volter9 can you share some tips while vanilla-fying? what can be replaced with what, caveats, tips and so on?

**Comment by volter9** [comment]
@sapegin yes, I understand. What I meant is: Social Likes provides other services beside Facebook, Tweeter, vk, ok, etc. Likely (it seems to be) doesn't need those services. Based on your proposal, I propose to create common repository with basic API that will be used by both plugins, but Social Likes going to extend this API with more services (so Likely wouldn't get them coz' they aren't needed there).

@iamstarkov I can't really tell how I did it, however, there's one website that can help with vanilla-fying stuff: http://youmightnotneedjquery.com

I'll tell you only one thing, nothing is impossible :wink:

**Comment by sapegin** [comment]
In that way it won’t help anybody ;-)

**Comment by volter9** [comment]
Well, I'm not the original author, though. I'm co-author. I can help with porting Social Likes to vanilla, but I can't join their API in one without Birman's agreement unless I'll fork likely and create my own plugin with own design called "Share buttons" haha :smiley:

Do you get what I mean?

**Comment by volter9** [comment]
Yesterday, Birman uploaded Likely on GitHub with its source code, if you're interested you can take a look at how I vanilla-fyed Likely:
https://github.com/ilyabirman/Likely

**Comment by iamstarkov** [comment]
so, we have jquery-less likely, so @sapegin you can take a look into it

**Comment by sapegin** [comment]
Of course I’ve looked into it. #149 is almost done actually.

**Comment by volter9** [comment]
:+1:

**Comment by sapegin** [comment]
Implemented in [Social Likes Next](https://github.com/sapegin/social-likes-next). Feel free to submit a pull request if you want it in the classic Social Likes too.
