### ISSUE TITLE
G+ counter limitation

### ISSUE THREAD

**Issue by volter9** [sapegin/social-likes#138]
Hello there!

I noticed that there's a G+ counter limitation. There's can be only one g+ counter on the page, and max. counter value is 10k. I could handle the first limitation, but I'm interested in solving the second limitation. Is there any possible way to workaround this limitation? Just wonder, thanks.

P.S.: I noticed this limitation when was toying around with `data-url` option.

**Comment by sapegin** [comment]
You should ask Google to provide a sane API for like counters.
