### ISSUE TITLE
Page meta data ignored for VK

### ISSUE THREAD

**Issue by AnotherOneAckap** [sapegin/social-likes#139]
Button for VK opens popup with 'title' argument, which overrides open graph metadata and so I can't just use it, I need to explicitly define "data-title" attribute.

**Comment by sapegin** [comment]
What kind of API you would like to see?

**Comment by AnotherOneAckap** [comment]
I think, you must not send "title" arg to VK popup, cause VK parses open graph meta data without problems.

**Comment by sapegin** [comment]
Fixed in [Social Likes Next](https://github.com/sapegin/social-likes-next). Feel free to submit a pull request if you want it in the classic Social Likes too.
