### ISSUE TITLE
Incorrect  post View  in social account

### ISSUE THREAD

**Issue by JuliaFlolova** [sapegin/social-likes#142]
Hello!
I use the plugin in my site WP sosial likes. 
1) In social network plugin added to the post titles of social networks
2) Vkontakte cuts post header

See my site
http://nichosy.ru/2015/09/16/etoj-devushke-59-let-uznajte-kak-ej-udaetsya- ostavatsya-v-takoj-
potryasayushhej-forme/

See Facebook  http://prntscr.com/8gy5nm
See Vkontakte http://prntscr.com/8gy60c

How I can fix this bags?

Thanks,
Julia

============================================

If you russian speaker developer.

Использую ваш плагин WP sosial likes для вордпресс.
При перепосте в соц сетях такие явления:

1) В ФБ и ВК вначале поста дописываются названия соцсетей, кнопки которых стоят у меня на сайте. В одноклассниках не смотрела. У меня нет там профиля.
Как убрать эти ненужные слова?

2) В ВК в перепосте обрезается заголовок поста. С чем это может быть связано?

Для наглядности даю ссылки на проект и на скриншоты соцсетей.

See project 
http://nichosy.ru/2015/09/16/etoj-devushke-59-let-uznajte-kak-ej-udaetsya- ostavatsya-v-takoj-

potryasayushhej-forme/

See Facebook  http://prntscr.com/8gy5nm
See Vkontakte http://prntscr.com/8gy60c

Буду очень признательна, если подскажете, с чем связаны эти явления и как их исправить  в коде плагина. Нужно срочно, не дожидаясь следующего релиза плагина.

**Comment by JuliaFlolova** [comment]
1) In social network plugin added to the post titles of social networks

it is possible due to the fact that I have changed the plugin code , finding the buttons before and after the post ? See attach screenshote

![social button](https://cloud.githubusercontent.com/assets/6319022/9904307/5a9541a6-5c85-11e5-8c05-d205beda43ac.jpg)

**Comment by sapegin** [comment]
It looks like that because of [your Open Graph tags](https://developers.facebook.com/tools/debug/og/object?q=http%3A%2F%2Fnichosy.ru%2F2015%2F09%2F16%2Fetoj-devushke-59-let-uznajte-kak-ej-udaetsya-ostavatsya-v-takoj-potryasayushhej-forme%2F).

The second part is definitely not about the Social Likes jQuery plugin.

**Comment by JuliaFlolova** [comment]
Thank you!
