### ISSUE TITLE
Tweet Count Not Displaying

### ISSUE THREAD

**Issue by mgspielman** [sapegin/social-likes#143]
Over the last couple days, my social-likes buttons have not been able to display a tweet count. It is happening on the demo page too: http://sapegin.github.io/social-likes/

Anyone know why this is happening?

On this test page, I added Twitter's own Tweet button below the social-likes buttons. The problem doesn't seem to be on Twitter's end: http://www.abort73.com/site/social-test/

**Comment by sapegin** [comment]
Both buttons on your test page work fine, as well as on the plugin’s demo page.

![](http://wow.sapegin.me/image/172K2j3I0A14/Image%202015-09-25%20at%2010.58.06%20PM.png)

**Comment by mgspielman** [comment]
Thanks for your quick response! I'm testing on an iMac, Powerbook, iPhone, and Windows laptop. None of them are displaying the tweet count. However, if I turn Wifi off on my iPhone, the tweet count shows up. The problem seems to be tied to my network. Have you every heard of something like that happening before?

![screen](https://cloud.githubusercontent.com/assets/7569362/10112452/4ad97018-63a9-11e5-902d-2c8aa3a2f25e.jpg)
