### ISSUE TITLE
VK.Share object gets overwritten by social-likes script

### ISSUE THREAD

**Issue by h8every1** [sapegin/social-likes#144]
Hello!

I have included original VK share script (https://vk.com/dev/share_details) on my page

    <script type="text/javascript" 
    src="http://vk.com/js/api/share.js?90" charset="windows-1251"
    </script>

But the `window.VK.Share` object gets overwritten by social-likes included later in the page:
https://github.com/sapegin/social-likes/blob/master/src/social-likes.js#L81

This breaks other share buttons on the page, because `VK.Share.button` method is not set now.

Also if I change order of files and first include `social-likes` and then vk.share script, VK counter in social-likes is broken, too.

**Comment by sapegin** [comment]
1. That’s because VK doesn’t provide normal API and we have to use hacks.

2. You shouldn't use original share buttons and Social Likes on the same page.
