### ISSUE TITLE
Twitter shutting off share counts soon (via JSON)

### ISSUE THREAD

**Issue by pagelab** [sapegin/social-likes#147]
https://blog.twitter.com/2015/hard-decisions-for-a-sustainable-platform

This will happen in November 20, and will affect pretty much [every share button](http://warfareplugins.com/is-twitter-seriously-removing-share-counts-why-would-they-do-this/) out there. 

Looks like that the much more complex [REST API](https://dev.twitter.com/rest/public) will be the only choice to grab share counts.

Will you just remove the support for the twitter share counter?

**Comment by sapegin** [comment]
Thanks for the links. That is very good news. That means I could make much simpler version of the Social Likes if I discontinue all the other counters.

**Comment by pagelab** [comment]
Yes, will be simpler indeed. But counters are a very relevant feature to encourage sharing, would be nice to maintain it at least in the supported platforms.

**Comment by sapegin** [comment]
Sure.

**Comment by kinday** [comment]
> But counters are a very relevant feature to encourage sharing

I share something because I want to share and there’s nothing about numbers indeed.

**Comment by arturi** [comment]
Without counters there is https://github.com/ireade/custom-social-buttons.

**Comment by sapegin** [comment]
@arturi There are dozens of buttons without counters. Not reason to use that one, especially if they require jQuery too ;-)

**Comment by arturi** [comment]
Yeah, sure you can write your own in few lines, if it only needs to open a sharing pop-up window. What I’d like the ideal library to do is to let me pick and choose any number of services I want and a button I want to use for the specific service. Say, native Facebook like that will load asynchronously, only when needed, and then custom sharing for Twitter and Google Plus.

**Comment by sapegin** [comment]
@arturi “if it only needs to open a sharing pop-up window” — if it’s the only thing you need.

I don’t see any reason to use native buttons.

**Comment by arturi** [comment]
As I explained, in Facebook like is not the same as share, and in VK too — it is a way to show your readers what you liked, without posting it to your timeline, and a also way to show the author your appreciation for his work.

But I do remember your opinion about it :)
