### ISSUE TITLE
Doesn't work in firefox last version

### ISSUE THREAD

**Issue by fabricek** [sapegin/social-likes#148]
I ve used interactive builder to generate the code. In the zip provided you have an example.
This works well with chrome/safari/IE.
But **not at all with firefox** last version (41.02 for information but it's not the matter). Nothing appear. The usual text appear but no the share(s) bar. Empty the cache but no success. Check on nginx/windows at home and debian server to. Really strange. Try differents downloads too. 
Firebug seem to work without any complaints. I really need your help to make this beautifull work/plugin up.

**Comment by sapegin** [comment]
Works fine for me:

!http://wow.sapegin.me/image/1x0p2U3A2H0J/Image%202015-11-02%20at%205.47.59%20PM.png!

**Comment by fabricek** [comment]
I am not surprised by your answer. Everything works fine in all other browsers. Anyway  my problem is still here.
- So I think there's a conflict with my firefox modules/plugins. 

Maybe you have a better idea of ​​what's going on?

I'll look at this and if I find something interresting to share I would tell you. Thank you for your answer and your good job.

**Comment by sapegin** [comment]
I have no idea. Do you have any errors in DevTools console or networks tab?
