### ISSUE TITLE
Share to Skype

### ISSUE THREAD

**Issue by Murilirum** [sapegin/social-likes#150]
With the release of [share to skype](http://blogs.skype.com/2015/11/04/introducing-share-button-effortless-sharing-that-sparks-richer-conversations/) I think having the built in functionality here on social likes would be a pretty good option to consider. I'll probably factor it in regardless but this would be as an out-of-the-box option I would personally like to see.

**Comment by sapegin** [comment]
I don’t believe that anyone will use this button and I hope Skype will die soon anyway. But you can always add your own buttons.

**Comment by Murilirum** [comment]
Haha fair enough @sapegin I know it's still a relatively popular platform for communication and sharing so I'll probably take on adding skype as a weekend project, would it be something you'd consider if a PR was made or should I just leave it alone?

**Comment by sapegin** [comment]
I’ll merge a PR to the [contrib folder](https://github.com/sapegin/social-likes/tree/master/contrib), not to the core.
