### ISSUE TITLE
Uncaught TypeError: Illegal invocation

### ISSUE THREAD

**Issue by Dmatafonov** [sapegin/social-likes#152]
Hi! I Have on click devtool error from jquery

```javascript
Uncaught TypeError: Illegal invocation
```
Have no idea what to look and what to fix. Jquery 1.11.1. Any thoughts?

**Comment by sapegin** [comment]
Can you share it somewhere so I could debug it?

**Comment by Dmatafonov** [comment]
Don't know what to share actually. We have regular jquery install, I added your script, buttons appera normal.

Digging in code. Looks like uikit tooltops conflict with your script in some way.

**Comment by Dmatafonov** [comment]
yep. removed uikit tooltip and now it works

**Comment by Dmatafonov** [comment]
think you should close issue, uikit is buggy - no need to determine which bug is it now
