### ISSUE TITLE
Ajax loaded elements (posts)

### ISSUE THREAD

**Issue by Dmatafonov** [sapegin/social-likes#153]
Look like social likes work only on static pages, on document ready.
In ajax-loaded posts I don't get buttons at all.

![image](https://cloud.githubusercontent.com/assets/8863854/11241129/b7aa7e7c-8e00-11e5-9575-bc4ba53aeacf.png)

Pls consider in future releases usage of mutation events, so we don't have to call plugin each time content is loaded. Thanks

**Comment by sapegin** [comment]
Right now you need to [initialize it manually](https://github.com/sapegin/social-likes#manual-initialization).

If you know a good way to make it better pull requests are appreciated.

**Comment by Dmatafonov** [comment]
dont know how to make pull requests :(

Here is the very short code I've added to the very bottom of your script to listen mutations and auto-add social likes. If you find it usefull, pls add.

```javascript
//Global mutations listener
(function(){
    //Cross browser creation of mutation object
    var MutationObserverLikes;
    if (typeof WebKitMutationObserver !== 'undefined') {
        MutationObserverLikes= WebKitMutationObserver;
    }
    else {
        MutationObserverLikes= MutationObserver;
    }

    //If browser can handle mutations
    if (typeof MutationObserverLikes !== 'undefined') {

        //Listen mutations
        var SocialLikesObserver = new MutationObserverLikes( function (mutations) {
            mutations.forEach(function(mutation){

                if (mutation.addedNodes.length) { //chack all added nodes
                    for (var j = 0; j < mutation.addedNodes.length; j++) {
                        var node = mutation.addedNodes[j];
                        $(node).find('.social-likes').each(function(){
                            $(this).socialLikes(); //make plugin to newrly added nodes
                        })
                    }
                }

            })
        });

        //Start listening
        SocialLikesObserver.observe(document, {
            childList: true, //listen nodes
            attributes: false, //don't listen attributes change
            characterData: false, //hz
            subtree: true, //listen descendants
            attributeOldValue: false, //no need to listen
            characterDataOldValue: false //no attribute check
        });

    }
})();
```

**Comment by Dmatafonov** [comment]
I'd put it as separate file, couse it works only if you initialize plugin standard way, passing options in element attribues. And it's not needed on static websites not loaded with ajax like slon.ru (where i found it)
