### ISSUE TITLE
Twitter counters no longer working

### ISSUE THREAD

**Issue by ninetienne** [sapegin/social-likes#157]
See here: http://stackoverflow.com/questions/33876953/how-i-can-get-twitter-count-now 

Please remove counters from the Twitter buttons, they are not going back: https://twittercommunity.com/t/a-new-design-for-tweet-and-follow-buttons/52791

**Comment by sapegin** [comment]
Are you kidding or just trolling?

https://github.com/sapegin/social-likes/releases/tag/3.0.15
