### ISSUE TITLE
social-likes_notext with social-likes_vertical

### ISSUE THREAD

**Issue by systems-rebooter** [sapegin/social-likes#163]
`social-likes_notext` with `social-likes_vertical` seems not working very nice and shows background
 text space

<img width="195" alt="screen shot 2015-12-10 at 11 34 15" src="https://cloud.githubusercontent.com/assets/8888190/11711950/bfacfc7e-9f32-11e5-8fd3-0c80e691bd0b.png">

**Comment by sapegin** [comment]
Feel free to submit a pull request.
