### ISSUE TITLE
v3.0.15 - Google+ and Twitter Counters not Show Up

### ISSUE THREAD

**Issue by systems-rebooter** [sapegin/social-likes#164]
Hello,

Looks like Google+ and Twitter counters not showing up in the latest version (3.0.15). 
Meanwhile, Facebook, Vkontakte and Pinterest working nicely. 

I've tried to reproduce it via https://github.com/sapegin/social-likes#counters-dont-work and still nothing...

Web-site URL: https://allremix.es

Site counters with empty `data-url`: 

<img width="263" alt="screen shot 2015-12-10 at 12 57 13" src="https://cloud.githubusercontent.com/assets/8888190/11713726/d28ba0d8-9f3d-11e5-9b39-51da96d4fecd.png">

Counters with `data-url="http://google.com"`:

<img width="357" alt="screen shot 2015-12-10 at 12 25 32" src="https://cloud.githubusercontent.com/assets/8888190/11713738/e3a0a8d2-9f3d-11e5-832f-86cc1d9a418d.png">

Chrome debugging showing up only 3 requests (For Facebook, Vkontakte and Pinterest accordingly): 

<img width="1792" alt="screen shot 2015-12-10 at 12 54 52" src="https://cloud.githubusercontent.com/assets/8888190/11713777/15d32168-9f3e-11e5-9b3c-457b6a23bf9d.png">

On demo-page http://sapegin.github.io/social-likes/ Google+ and Twitter counters not showing up as well for some reason:

<img width="1792" alt="screen shot 2015-12-10 at 16 05 32" src="https://cloud.githubusercontent.com/assets/8888190/11717275/14202eb4-9f58-11e5-9690-b2ea6d89a717.png">

Thanks!

**Comment by sapegin** [comment]
Google works fine for me, Twitter was disabled in 3.0.15.
