### ISSUE TITLE
Google+ counter not working on demo page

### ISSUE THREAD

**Issue by systems-rebooter** [sapegin/social-likes#165]
Google+ counter not working. It's not working on demo page as well, which is using latest social-likes.js
http://sapegin.github.io/social-likes/ Detailed info in  #164

<img width="1792" alt="screen shot 2015-12-10 at 16 05 32" src="https://cloud.githubusercontent.com/assets/8888190/11739673/d2c3955c-9ff5-11e5-87f5-f37d744c6324.png">

@sapegin before marking this issue as invalid like #164 and locking comments to it I would be very grateful if you tried to help, so I can debug more precisely  and figure out why exactly Google+ counters  were not working. If you don't have time to help me out - I'll understand, but maybe some collaborators do. 

Anyway, thanks for the great piece of software! It's the most cool one out there.

**Comment by scream4ik** [comment]
Today i had problem with G+ too.

I saw this error in console
![]
(http://pic.oldmin.org/do_not_del/5.jpg)

I changed data type to jsonp and it works

![]
(http://pic.oldmin.org/do_not_del/6.jpg)

**Comment by pagelab** [comment]
@scream4ik's solution worked for me.

social-likes.js, line 137:

````
		plusone: {
			// HTTPS not supported yet: http://clubs.ya.ru/share/1499
			counterUrl: isHttps ? undefined : 'http://share.yandex.ru/gpp.xml?url={url}',
			counter: function(jsonUrl, deferred) {
				var options = services.plusone;
				if (options._) {
					// Reject all counters except the first because Yandex Share counter doesn’t return URL
					deferred.reject();
					return;
				}

				if (!window.services) window.services = {};
				window.services.gplus = {
					cb: function(number) {
						if (typeof number === 'string') {
							number = number.replace(/\D/g, '');
						}
						options._.resolve(parseInt(number, 10));
					}
				};

				options._ = deferred;
				// $.getScript(makeUrl(jsonUrl))
				// 	.fail(deferred.reject);
				$.ajax({
					url: makeUrl(jsonUrl),
					dataType: 'jsonp',
					success: function(number){
						if (typeof number === 'string') {
							number = number.replace(/\D/g, '');
						}
						options._.resolve(parseInt(number, 10));
					}
				})
				.fail(deferred.reject);
			},
			popupUrl: 'https://plus.google.com/share?url={url}',
			popupWidth: 700,
			popupHeight: 500
		},
````

**Comment by sapegin** [comment]
Thanks for the investigation! Can anyone send a pull request for that?

**Comment by scream4ik** [comment]
Done

**Comment by volter9** [comment]
Guys, all you need to do is to change URL... See this [commit](https://github.com/ilyabirman/Likely/commit/772ac32adeeacb79be9c4cfddeb1de1449623c4d#diff-d3f9690c63758354bf15391c8abad93cR10)

**Comment by sapegin** [comment]
@volter9 Of course we already have it. And it’s not only URL change.

**Comment by volter9** [comment]
Well, for likely, changing the URL only fixed the error.

**Comment by sapegin** [comment]
Fixed now.
