### ISSUE TITLE
Стили накладываются друг на друга

### ISSUE THREAD

**Issue by edbond88** [sapegin/social-likes#173]
Привет! У меня на проекте компоненты из бовера автоматически подключаются к проект, те все файлы в том числе и стили. Из-за этого стили кнопок накладываются друг на друга.
Мне кажется лучше было бы сделать стайлинг кнопки по задаваемому классу для обертки кнопок, а не по подключаемому файлу, а все стили засунуть в один файл.
![screenshot_1](https://cloud.githubusercontent.com/assets/1949927/12168787/3302a708-b53d-11e5-93dd-227974f124d2.png)

**Comment by sapegin** [comment]
Please use English when posting to this project.
