### ISSUE TITLE
Не работают счетчики на твиттере и ВК

### ISSUE THREAD

**Issue by exzept** [sapegin/social-likes#175]
Почему-то не показываются количество счетчики ВК и Twitter, хотя я пробовал добавлять, сначала появляется цифра 1, затем после обновления страницы исчезает.
Скрин: http://puu.sh/mwVI5/82289e095d.png
Пациент: http://xn--e1agfw6a0bt.xn--p1ai/

Why does not show the amount of VC counters and Twitter, though I tried to add the first number 1 appears, then disappears when the page is updated.
Screen: http://puu.sh/mwVI5/82289e095d.png
Patient: http://xn--e1agfw6a0bt.xn--p1ai/

**Comment by sapegin** [comment]
https://github.com/sapegin/social-likes#counters-dont-work
