### ISSUE TITLE
trouble with https://sapegin.github.io/social-likes/

### ISSUE THREAD

**Issue by lfender6445** [sapegin/social-likes#177]
https://sapegin.github.io/social-likes/ 

getting jquery is not defined when i pop open console

**Comment by sapegin** [comment]
Where did you get this link? Works fine with HTTP.

**Comment by sapegin** [comment]
I’ve replace a link to jQuery so the page now works but it still complains about the proxy.php.

**Comment by lfender6445** [comment]
oh i see. i have a chrome extension that prefers encrypted connections if they are available.
