### ISSUE TITLE
How and where counters recorded history?

### ISSUE THREAD

**Issue by dokxpi** [sapegin/social-likes#178]

**Comment by sapegin** [comment]
Not sure I understand the question.

**Comment by dokxpi** [comment]
How to store value button-counter?
![2016-02-29_190052](https://cloud.githubusercontent.com/assets/10334512/13401944/d2058764-df16-11e5-9d29-53450eb0ff2f.png)

**Comment by sapegin** [comment]
Where you store any other data in your app I suppose.
