### ISSUE TITLE
Counter for odnoklassniki

### ISSUE THREAD

**Issue by ideafm** [sapegin/social-likes#179]
Hi! If display counters, but page not shared yet then counter for odnoklassniki is -1 instead of 0. It's only for me?

**Comment by sapegin** [comment]
Works fine for me:

![](http://wow.sapegin.me/382D2O1s410f/Image%202016-03-04%20at%209.11.12%20PM.png)

**Comment by ideafm** [comment]
That's what I see: `ODKL.updateCount('0','-1');`
Could it be because i'm using connection to host via VPN? Maybe not have enough permissions

**Comment by sapegin** [comment]
I have no idea. Anyway it’s not the right place for questions about OK API.
