### ISSUE TITLE
[Safari] Social Share "Plain Link Style" No Icons

### ISSUE THREAD

**Issue by sergeychernyakov** [sapegin/social-likes#185]
Safari:

![2016-08-08 16 16 44](https://cloud.githubusercontent.com/assets/1222138/17482905/75aa329a-5d8c-11e6-89e1-2ae8163065d0.png)

Works fine in Chrome:

![2016-08-08 16 20 31](https://cloud.githubusercontent.com/assets/1222138/17482918/80a19940-5d8c-11e6-8024-25e3e2e2d7aa.png)

**Comment by sapegin** [comment]
Works fine for me:

![image 2016-08-08 at 4 45 01 pm](https://cloud.githubusercontent.com/assets/70067/17483718/775c410a-5d87-11e6-80be-0a03de377782.png)

Feel free to submit a pull request if you think there’s a bug.
