### ISSUE TITLE
Global counter ? 

### ISSUE THREAD

**Issue by tergra** [sapegin/social-likes#188]
Hi guys ! :)

Is there a way to get the total number of shares on all the networks ?
And is it possible to put this total counter into the database for caching purposes ?  (I guess calling the counter for every share is slowing down the website a lot isn't it) 
  
Thanks a lot !!  :)

**Comment by sapegin** [comment]
Use `ready.social-likes` event to get total counter: https://github.com/sapegin/social-likes#readysocial-likes

If you care about performance (and you should) I’d just disable counters at all and use [Social Likes Next](http://social-likes-next.js.org/).
