### ISSUE TITLE
Facebook does not work counter

### ISSUE THREAD

**Issue by NesteA88** [sapegin/social-likes#192]
Good afternoon!

By clicking on the Facebook post on a social network button appears, but the counter is not changing. What could be the problem? Website - https://armymusic.ru

**Comment by sapegin** [comment]
That’s a desired behavior. You can update counters manually: https://github.com/sapegin/social-likes#popup_closedsocial-likes

**Comment by NesteA88** [comment]
The problem is not the fact that after pressing the button does not change the value of the counter, and that it does not work for the Facebook button. On the other counters all right.

**Comment by sapegin** [comment]
https://github.com/sapegin/social-likes#counters-dont-work

**Comment by NesteA88** [comment]
API requests results in Network tab in your browser’s developer tools - 
![- -1](https://cloud.githubusercontent.com/assets/24646955/21310496/0ddd5b46-c5fc-11e6-983e-c55502311cf1.jpg)
see screenshot

**Comment by sapegin** [comment]
If you report a bug make sure you use the latest version: this was fixed four months ago.
