### ISSUE TITLE
Problem with IE 8

### ISSUE THREAD

**Issue by oopros** [sapegin/social-likes#194]
Internet explorer 8 has error in Js with plugin

http://c2n.me/3FXJnIZ
How we can fix that?
Thanks!

**Comment by sapegin** [comment]
Looks like Vkontakte send something that IE8 can’t parse. Will it work with `counters="no"`?

**Comment by oopros** [comment]
If i swith of Vkontakte - it's work good!

**Comment by oopros** [comment]
how i can use Vkontakte, but with not mistake

**Comment by sapegin** [comment]
It’s better to ask them ;-) I’m pretty sure they don’t support IE8 for a long time.
