### ISSUE TITLE
The problem with Facebook button counter

### ISSUE THREAD

**Issue by NesteA88** [sapegin/social-likes#195]
Artem, good afternoon! I understand that you complete support on old project Social Likes, but maybe you will assist in the problem.

The problem follows. Ceased to be displayed on the counter Facebook button.

API requests results in Network tab in your browser’s developer tools - see screenshot 1

I looked like on your site http://social-likes.js.org/ it works - it's all right (see screenshot 2)

A few days ago everything worked well, the site did not do anything. What could be the problem?

Thank you in advance!
![1](https://cloud.githubusercontent.com/assets/24646955/21956081/fea26d06-da91-11e6-8f85-267babb8fcf8.jpg)
![2](https://cloud.githubusercontent.com/assets/24646955/21956082/feb5baf0-da91-11e6-97e4-05bb61b3c019.jpg)

**Comment by sapegin** [comment]
It works fine right now:

![image 2017-01-14 at 5 11 34 pm](https://cloud.githubusercontent.com/assets/70067/21956231/898553d6-da7c-11e6-90d9-39b1b859e3da.png)
