### ISSUE TITLE
share.yandex.ru/gpp.xml

### ISSUE THREAD

**Issue by toemanz** [sapegin/social-likes#202]
plusone: {
			counterUrl: protocol + '//share.yandex.ru/gpp.xml?url={url}&callback=?'

для получения циферок +1 используется указанный выше урл, так вот сегодня заметил он отдает 500 ошибку, надеюсь решится само собой - но тем не менее - уведомляю ;)

**Comment by sapegin** [comment]
Please use English when posting to this project.
