### ISSUE TITLE
not work +1 counter

### ISSUE THREAD

**Issue by toemanz** [sapegin/social-likes#203]
to get "+1" uses the this URL, 

plusone: {
counterUrl: protocol + '//share.yandex.ru/gpp.xml?url={url}&callback=?'

and he gives 500 error
2 week ago i say it in issue 202,

demo page error in  console:
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by sapegin** [comment]
Feel free to send a pull request with at fix.

**Comment by weltkind-dmitry-savinkov** [comment]
Hey) Change line to this)
counterUrl: n + "//plus.google.com/share?url={url}",

**Comment by yerzhant** [comment]
I'm getting this error:
Failed to load resource: the server responded with a status of 404 (Not Found)
https://share.yandex.ru/gpp.xml?url=https%3A%2F%2Fazan.kz%2Fahbar%2Fread%2Fv-kazahstane-vpervyie-zapuskaetsya-pervaya-platezhnaya-kartochka-10955&callback=jQuery224034881795501958957_1508165291936&_=1508165291937
