### ISSUE TITLE
Error 404 in console

### ISSUE THREAD

**Issue by nabidefacto** [sapegin/social-likes#207]
It seems that social likes uses yandex.ru
but it gives 404 error
https://share.yandex.ru/gpp.xml?url=http%3A%2F%2Fsocial-likes.js.org%2Fru%2F&callback=jQuery22005561533208318772_1508939015344&_=1508939015345

Could you please fix it?

**Comment by sapegin** [comment]
Fee free to submit a pull request with a fix.

**Comment by pagelab** [comment]
This happens because Google Plus share numbers [where turned off by Google recently](https://plus.google.com/110610523830483756510/posts/Z1FfzduveUo).

So, just remove the part the adds the call to retrieve Google Plus share numbers with Yandex in social-likes.js at line `116`:

```js
plusone: {
	counterUrl: protocol + '//share.yandex.ru/gpp.xml?url={url}&callback=?',
	convertNumber: function(number) {
		return parseInt(number.replace(/\D/g, ''), 10);
	},
	popupUrl: 'https://plus.google.com/share?url={url}',
	popupWidth: 500,
	popupHeight: 550,
},
```

**Comment by sapegin** [comment]
> Fee free to submit a pull request with a fix.
