### ISSUE TITLE
Pinterest: read media URL from meta tags

### ISSUE THREAD

**Issue by sapegin** [sapegin/social-likes#25]
```<meta property="og:image" content="{image_url}">```

or

```<link rel="image_src" href="{image_url}">```

Throw exception when one of meta tags or data-media attribute not specified.

**Comment by dems59** [comment]
Any update on this? I installed today, but the Pinterest button is not grabbing the OG image.

**Comment by sapegin** [comment]
@dems59 Pull requests are welcome.

**Comment by TITAN-UZ** [comment]
When the support OG META?

**Comment by sapegin** [comment]
I’m closing this for now. Feel free to submit a pull request if you need this.
