### ISSUE TITLE
add image to data-media for facebook share

### ISSUE THREAD

**Issue by buzzguy** [sapegin/social-likes#51]
is there a way for facebook share to also grab the data-media attribute so that it posts a specific image file rather than just the page and listing all possible images? an example would be buzzfeed's sharebox (http://www.buzzfeed.com/alanwhite/extreme-underwater-freediving-in-the-arctic) if you hover over an image and click on the facebook share. 

thanks!

**Comment by sapegin** [comment]
I’m closing this for now. Feel free to submit a pull request if you need this.
