### ISSUE TITLE
Custom data-media / data-%smth-to-share% for vk.com

### ISSUE THREAD

**Issue by magicpriest** [sapegin/social-likes#55]
Есть такая фича у VK API – шарить кастомную картинку, а не все картинки со страницы и шарить определенный текст с этой же страницы, как это реализовать в рамках social likes? Проект отличный, не хочется с него слезать, а шарить правильно хочется.

**Comment by sapegin** [comment]
I’m closing this for now. Feel free to submit a pull request if you need this.
