### ISSUE TITLE
Retina Icons

### ISSUE THREAD

**Issue by seinoxygen** [sapegin/social-likes#67]
As future enchacement use bigger icons for buttons to get them to work more nicely with mobile devices.

Little hint: http://code.tutsplus.com/tutorials/the-right-way-to-retinafy-your-websites--net-31793

Thanks for the plugin! :)

**Comment by sapegin** [comment]
Implemented in [Social Likes Next](https://github.com/sapegin/social-likes-next). Feel free to submit a pull request if you want it in the classic Social Likes too.
