### ISSUE TITLE
Linkedin Support

### ISSUE THREAD

**Issue by curttest** [sapegin/social-likes#72]
https://www.linkedin.com/countserv/count/share?url=

**Comment by pro100Hub** [comment]
:+1: 
@sapegin возникают сложности при добавлении к общему списку кнопок?
Аж с июля тянется реализация :(

**Comment by sapegin** [comment]
@pro100Hub Please use English when posting to this project.

**Comment by eugef** [comment]
+1 Would be great to have LinkedIn share

**Comment by apolukhin** [comment]
+1

**Comment by sapegin** [comment]
Implemented in [Social Likes Next](https://github.com/sapegin/social-likes-next). Feel free to submit a pull request if you want it in the classic Social Likes too.
